#!/bin/sh

# filename without path
name=`basename $0`

# function for changing file name or folder name
change_name(){
	if test -f $1 -o -d $1
	then
		path=$1				# full path to file or directory
		basename=$(basename "$path")	# file name or directory name
		dirname=$(dirname "$path")	# path without file name or current directory
		
		case $2 in
			l)	# change name to lowercase
				if test -f $1
				then
					newfile=$(echo "${basename%.*}" | tr '[:upper:]' '[:lower:]')		# change name without changing extension
					mv -- "$1" "$dirname/$newfile.${basename##*.}" 2>/dev/null; true	# move to new file
				elif test -d $1
				then
					newdir=$(echo "$basename" | tr '[:upper:]' '[:lower:]')
					mv "$1" "$dirname/$newdir/" 2>/dev/null; true
				fi
				;;
			u)	# change name to uppercase
				if test -f $1
				then
					newfile=$(echo "${basename%.*}" | tr '[:lower:]' '[:upper:]')
					mv -- "$1" "$dirname/$newfile.${basename##*.}" 2>/dev/null; true
				elif test -d $1
				then
					newdir=$(echo "$basename" | tr '[:lower:]' '[:upper:]')
					mv "$1" "$dirname/$newdir/" 2>/dev/null; true
				fi
				;;
			sed)	# change name with sed
				if test -f $1
				then
					newfile=$(echo "${basename%.*}" | sed $3)
					mv -- "$1" "$dirname/$newfile.${basename##*.}" 2>/dev/null; true
				elif test -d $1
				then
					newdir=$(echo "$basename" | sed $3)
					mv "$1" "$dirname/$newdir/" 2>/dev/null; true
				fi
				;;
		esac

	else
		echo "No such file or directory $1"
	fi
}

# do with command line arguments
r=n
l=n
u=n
s=n
h=n
pattern=''
while test "x$1" != "x"
do
	case "$1" in
		-r) r=y;;
		-l) l=y; u=n; s=n;;
		-u) u=y; l=n; s=n;;
		-h) h=y; l=n; u=n; r=n; s=n;;
		sed) s=y
		     l=n
		     u=n
		     if test ! -z "$2"
		     then
			     pattern=$2
		     else
			     echo "Missing sed pattern."
		     fi
		     shift
		     ;;
		*)
			if test $r = "y"	# change name recursively
			then
				if test -d $1	# change name only if it is directory
				then
					# firstly, find and change the current directory name and all the subdirectory
					# secondly, find and change all the file name in this current directory

					listdir=`find $1 -depth -type d -name "*"`
					if test $l = "y"
					then
						for ld in $listdir
						do
							change_name "$ld" "l"
						done
						newdir=$(echo "$1" | tr '[:upper:]' '[:lower:]')	# find a new directory name after changing
						listfile=`find $newdir -depth -type f -name "*"`
						for lf in $listfile
						do
							change_name "$lf" "l"
						done
					elif test $u = "y"
					then
						for ld in $listdir
						do
							change_name "$ld" "u"
						done
						newdir=$(echo "$1" | tr '[:lower:]' '[:upper:]')
						listfile=`find $newdir -depth -type f -name "*"`
						for lf in $listfile
						do
							change_name "$lf" "u"
						done
					elif test $s = "y"
					then
						for ld in $listdir
						do
							change_name "$ld" "sed" "$pattern"
						done
						newdir=$(echo "$1" | sed $pattern)
						listfile=`find $newdir -depth -type f -name "*"`
						for lf in $listfile
						do
							change_name "$lf" "sed" "$pattern"
						done
					fi
				else
					echo "$1 is not a directory"
				fi
			else	# change name of specified files and directory
				if test $l = "y"
				then
					change_name "$1" "l"
				elif test $u = "y"
				then
					change_name "$1" "u"
				elif test $s = "y"
				then
					change_name "$1" "sed" "$pattern"
				fi
			fi
			;;
	esac
	shift
done

# something for help
if test $h = "y"
then
cat<<EOT 1>&2
usage:
  $name [-r] [-l|-u] <file/directory names>
  $name [-r] <sed pattern> <file/directory names>
  $name [-h]

$name correct syntax examples:
  $name -l LEVEL1_DIR/ LEVEL1_FILE.py
  $name -u level1_dir/ level1_file.py
  $name -r -u level1_dir/
  $name sed 's/level/changed_level/' level1_dir/ level1_file.py
  $name -r sed s/level/changed_level/ level1_dir/

$name incorrect syntax example:
  $name -r -u level1_file.py
  $name level1_file.py
  $name sed this_is_wrong_pattern level1_file.py
EOT
fi
